import { ScaffoldPage } from "@/components/admin/ScaffoldPage";

export default function InquiriesPage() {
  return (
    <ScaffoldPage
      eyebrow="Operate"
      title="Inquiries"
      description="Every WhatsApp/phone/email lead generated by a listing. The single most important conversion metric pre-checkout."
      schema={["inquiries", "v_seller_health (response_rate)"]}
      workflows={[
        "WhatsApp deep-link click writes an inquiry row (channel='whatsapp')",
        "Seller marks responded=true; system computes response_rate (rolling 30d)",
        "Auto-nudge sellers with rate < 50% via Beem SMS",
        "Filter: unresponsive > 48h surfaces in v_attention_queue"
      ]}
      next="Server route /api/inquiries/record (POST) that logs the click before the WhatsApp redirect. Page: filterable table with quick 'Mark responded' action."
    />
  );
}
